name: kasbli_merchant
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  flutter_screenutil: ^5.9.3
  lottie: ^3.3.1
  google_fonts: ^6.2.1
  flutter_intl_phone_field: ^0.0.7
  easy_localization: ^3.0.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0
  retrofit: ^4.4.2
  pretty_dio_logger: ^1.4.0
  flutter_bloc: ^9.1.1
  dio: ^5.8.0+1
  another_flushbar: ^1.12.30
  pinput: ^5.0.1
  device_preview: ^1.2.0
  animated_notch_bottom_bar: ^1.0.3
  cached_network_image: ^3.4.1
  skeletonizer: ^1.4.3
  like_button: ^2.1.0
  curved_navigation_bar: ^1.0.6
  easy_notify: ^1.0.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  
  # Permission handling
  permission_handler: ^12.0.1
  get_it: ^8.2.0
  equatable: ^2.0.7
  url_launcher: ^6.3.2
  carousel_slider: ^5.1.1
  flutter_file_dialog: ^3.0.2
  path_provider: ^2.1.5
  package_info_plus: ^8.0.2
  flutter_html: ^3.0.0
  flutter_map: ^8.2.1
  geolocator: ^14.0.2
  google_maps_flutter: ^2.13.1
  graphic: ^2.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  retrofit_generator: '>=8.0.0 <10.0.0' # for Dart 3.3 use ^9.0.0
  build_runner: ^2.3.3
 
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/temp/
    - assets/translations/
    - assets/animation/